### ISSUE TITLE
Want to help to add new language translation 

### ISSUE THREAD

**Issue by pratomoastan** [thuutin/android_device_asus_a500cg#29]
uhh hi guys , i was here to support this project , and i want to help translate this builds to the another language , especially indonesian , so ill need some equipment to do it . 
thanks !!

**Comment by tank0412** [comment]
What?
Developer called languages_full.mk config so this rom supports all languages which support AOSP.
I am sure that indonesian language is included

**Comment by pratomoastan** [comment]
yes i know that , but that translation was not perfect ( misspelled , too formal , etc) , so i want to fix the wrong ones , to became the right ones .

**Comment by thuutin** [comment]
You  could contribute to the official cyanogenmod    tree so that many people can benefit from
